name: tasker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.5
  path: ^1.8.3
  path_provider: ^2.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  table_calendar: ^3.0.6
  flutter_launcher_icons: ^0.9.2

flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Comfortaa-Regular.ttf
    - assets/fonts/Comfortaa-Bold.ttf
    - assets/fonts/Montserrat-Regular.ttf
    - assets/fonts/Montserrat-Bold.ttf
    - assets/images/logo.png

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
